services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      BACKEND_URL: http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
